//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        Workout()
        { }
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> tickets { get; set; }
        public Nullable<int> Coach { get; set; }
        public Nullable<int> View_training { get; set; }
    
        public virtual Coach Coach1 { get; set; }
        public virtual SeasonTicket SeasonTicket { get; set; }
        public virtual TypeOfTraining TypeOfTraining { get; set; }
    }
}
